# Generated by Django 4.2.11 on 2024-05-31 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_donation_is_taken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['is_taken', 'pick_up_date']},
        ),
    ]
